GET http://localhost:5000/subscribers

###
GET http://localhost:5000/subscribers/5e286a372a0057440cab45e5

###
DELETE http://localhost:5000/subscribers/5e28794bdee9ca39702907af

###
POST http://localhost:5000/subscribers
Content-Type: application/json

{
"name": "Martin Shungoh",
"subscribedToChannel": "Ahoy Matey!!!"
}

###
PATCH  http://localhost:5000/subscribers/5e2897b50845fb57f0812638
Content-Type: application/json

{
"name": "Martin Shungoh",
"subscribedToChannel": "Ahoy! Ahoy! Fornication Pleeeeeee!!!"
}


###




















// Get ALL Records
GET http://localhost:5000/photos

// Get One Record
###
GET http://localhost:5000/photos/921

//Delete One Record
###
DELETE http://localhost:5000/photos/5e28794bdee9ca39702907af

// Add One Record
###
POST http://localhost:5000/photos
Content-Type: application/json

{
"_id": "930",
"title": "Ebisu Town",
"url": "https://images.mangafreak.net/mangas/one_piece/one_piece_930/one_piece_930_1.jpg",
"url_2": ""
}

// Update One Record
###
PATCH  http://localhost:5000/photos/5e2897b50845fb57f0812638
Content-Type: application/json

{
"name": "Martin Shungoh",
"url": "Ahoy! Ahoy! Fornication Pleeeeeee!!!"
}
###
















// Get ALL Records
GET http://localhost:3000/users/all
// Get One Record
###
GET http://localhost:3000/users/5e29a3bb1f21662b50621ebd

//Delete One Record
###
DELETE http://localhost:3000/users/5e29a3bb1f21662b50621ebd

// Add One Record
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
"email": "admin4@gmail.com",
"password": "ashyslashy"
}

// Add One Record
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
"email": "admin4@gmail.com",
"password": "ashyslashy"
}

// Update One Record
###
PATCH  http://localhost:3000/users/5e29b1281756354344ef9acd
Content-Type: application/json

{
"email": "admin54@gmail.com",
"password": "TheGameBeganBeforeItEnded"
}